name: Self-test action

on:
  push:
    branches:
      - master
      - main
  pull_request:

# ATTENTION
# This is a self-test pipeline and it is *NOT* intended to be used as a base/quickstart on how to
# use the action. Please refer to the examples in the README.md file for that

jobs:
  test_local_power_dns:
    runs-on: ubuntu-latest
    name: Test run the e2e test on powerdns local testdata
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
      - name: Run action for PowerDNS (exporter based)
        uses: ./
        with:
          spec_path: test/testdata/powerdns/powerdns-e2e.yml
          account_id: ${{ secrets.ACCOUNT_ID }}
          api_key: ${{ secrets.API_KEY }}
          license_key: ${{ secrets.LICENSE_KEY }}
          retry_seconds: 60
          retry_attempts: 15
  test_local_kafka:
    runs-on: ubuntu-latest
    name: Test run the e2e test on kafka local testdata
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
      - name: Run action for Kafka (sample based)
        uses: ./
        with:
          spec_path: test/testdata/kafka/kafka-e2e.yml
          account_id: ${{ secrets.ACCOUNT_ID }}
          api_key: ${{ secrets.API_KEY }}
          license_key: ${{ secrets.LICENSE_KEY }}
          retry_seconds: 60
          retry_attempts: 15
  test_local_k8s:
    # To be able to use driver=none we have to provide a CRI that kubelet allows.
    # Or we do the research to use `ubuntu-latest` or we should keep to an old version of Ubuntu and Kubernetes
    # so this test can run using Docker as a CRI.
    runs-on: ubuntu-20.04
    name: Test run the e2e test on k8s local testdata
    steps:
      - name: checkout-repository
        uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version-file: go.mod
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: v1.20.0
          kubernetes version: v1.21.4
          driver: none  # required for nri-kubernetes, as metrics gathered for the host are tested as well
      - name: Setup Helm
        run: |
          chmod go-r /home/runner/.kube/config
          helm repo add stable https://charts.helm.sh/stable
          helm repo add newrelic https://helm-charts.newrelic.com
          helm repo update
      - name: Run action for K8s (sample based without agent)
        uses: ./
        with:
          spec_path: test/testdata/k8s/k8s-e2e.yml
          account_id: ${{ secrets.ACCOUNT_ID }}
          api_key: ${{ secrets.API_KEY }}
          license_key: ${{ secrets.LICENSE_KEY }}
          retry_seconds: 60
          retry_attempts: 15
          agent_enabled: "false"
